"""
Django settings for talent_solutions project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ═══════════════════════════════════════════════════════════════
# ENVIRONMENT DETECTION (like Spring Boot profiles!)
# ═══════════════════════════════════════════════════════════════
# Set ENVIRONMENT variable to switch between configs:
#   - 'local'      → uses .env.local (development)
#   - 'production' → uses .env.production (server)
#
# How to set:
#   Windows:   set ENVIRONMENT=production
#   Linux:     export ENVIRONMENT=production
#   Default:   local (if not set)
# ═══════════════════════════════════════════════════════════════

ENVIRONMENT = os.getenv('ENVIRONMENT', 'local')

# Load the appropriate .env file based on environment
if ENVIRONMENT == 'production':
    env_file = BASE_DIR / '.env.production'
    print(f"[PRODUCTION] Loading config from {env_file}")
else:
    env_file = BASE_DIR / '.env.local'
    print(f"[LOCAL] Loading config from {env_file}")

# Load environment variables from the selected file
load_dotenv(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ufhxt@f4&l+(d5&b_q-#xpyqu@zbv5y@5y#+*v-ldix404f2d)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Trust X-Forwarded-Proto header from nginx (for HTTPS detection behind reverse proxy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'main'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.JWTAuthenticationMiddleware',
]

ROOT_URLCONF = 'talent_solutions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.company_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'talent_solutions.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_data' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'main.User'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': not DEBUG,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

# Google OAuth Settings
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET')

# Brevo Email (SMTP relay)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('BREVO_SMTP_LOGIN')
EMAIL_HOST_PASSWORD = os.environ.get('BREVO_SMTP_PASSWORD')

# Sender addresses for Talent Solutions
# All three addresses are verified in Brevo:
# - no-reply@talentsolutions.com.np (one-way communications)
# - hr@talentsolutions.com.np (displayed as "Talent Solutions HR")
# - recruitment@talentsolutions.com.np (displayed as "Talent Solutions Recruitment")
EMAIL_SENDERS = {
    'welcome':       'no-reply@talentsolutions.com.np',       # application received confirmation → applicant
    'hr':            'hr@talentsolutions.com.np',             # application status updates (rejection, shortlisted, etc.) → applicant
    'recruitment':   'recruitment@talentsolutions.com.np',    # new application alerts → internal team
    'support':       'no-reply@talentsolutions.com.np',       # OTP, password reset, verification → user
    'notifications': 'no-reply@talentsolutions.com.np',       # general notifications → user
}

# Base URL used in email links (set SITE_URL in .env when deployed)
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
