# Generated by Django 5.1.6 on 2026-01-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Official company name', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company/')),
                ('tagline', models.CharField(blank=True, help_text='Short slogan or motto', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('industry', models.CharField(blank=True, help_text='Industry type', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Secondary phone', max_length=20, null=True)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('postal_code', models.CharField(help_text='ZIP/Postal code', max_length=20)),
                ('about', models.TextField(blank=True, help_text='About us description', null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='Year company was founded', null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], help_text='Employee count range', max_length=20, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('startup', 'Startup'), ('ngo', 'NGO'), ('government', 'Government')], help_text='Type of company', max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'company',
            },
        ),
    ]
