# Generated by Django 5.1.6 on 2026-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='', help_text='Employer company name', max_length=200),
        ),
    ]
