# Generated by Django 5.1.6 on 2026-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='fooding',
            field=models.BooleanField(default=False, help_text='Is food provided?'),
        ),
        migrations.AddField(
            model_name='job',
            name='lodging',
            field=models.BooleanField(default=False, help_text='Is lodging/accommodation provided?'),
        ),
        migrations.AddField(
            model_name='job',
            name='overtime_available',
            field=models.BooleanField(default=False, help_text='Is overtime available?'),
        ),
    ]
