# Generated by Django 5.1.6 on 2026-02-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', help_text='Authentication provider used for registration', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth unique user ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='External profile picture URL (e.g., from Google)', null=True),
        ),
    ]
