# Generated by Django 5.1.6 on 2026-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_replace_user_skills_with_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
