# Generated by Django 5.1.6 on 2026-02-03 15:22

import main.models.application_model
import main.models.auth_model
import main.models.user_document_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_rejection_reason_to_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.application_model.upload_application_cv),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='passport_photo',
            field=models.ImageField(upload_to=main.models.application_model.upload_application_passport),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=main.models.auth_model.upload_profile_picture),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.user_document_model.upload_document_cv),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_document_model.upload_document_passport),
        ),
    ]
