# Generated by Django 5.1.6 on 2026-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_update_upload_to_conventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True, help_text='Whether the user has verified their email via OTP'),
            preserve_default=False,
        ),
    ]
