# Generated by Django 5.0.2 on 2026-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email via OTP'),
        ),
    ]
