# Generated by Django 5.1.6 on 2026-02-07 16:08

import main.models.team_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('position', models.CharField(help_text='Job title/role', max_length=150)),
                ('bio', models.TextField(help_text='Short bio (max 300 characters)', max_length=300)),
                ('photo', models.ImageField(help_text='Team member photo (recommended: square image, min 400x400px)', upload_to=main.models.team_model.upload_team_photo)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +9779841234567)', max_length=20, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first (0, 1, 2, ...)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active members are shown on the website')),
                ('created_at', models.BigIntegerField(editable=False)),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
