# Generated by Django 5.1.6 on 2026-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tiktok',
            field=models.URLField(blank=True, help_text='TikTok profile URL', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='WhatsApp business URL', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
    ]
